### ISSUE TITLE
[bug] The Pathshala link is wrong. 

### ISSUE THREAD

**Issue by rajarshimaitra** [Bitshala/website-v2#103]
The `pathshala` link in the about description goes to our discord. 

Instead, it should go to https://en.banglapedia.org/index.php/Pathshala

If we can find a better description of Pathshala, we can add it. So far, this seems complete enough to me.

**Comment by rajarshimaitra** [comment]
Another good description.. https://edurev.in/question/343140/What-is-pathshalas-

**Comment by keraliss** [comment]
Which one should I use? The first one or the second one?

**Comment by rajarshimaitra** [comment]
> Which one should I use? The first one or the second one?
Open to anyone.
Proposed PR with the first.  https://github.com/Bitshala/website-v2/pull/104
