### ISSUE TITLE
[V2] New Page: Bitcoin Reading Clubs

### ISSUE THREAD

**Issue by rajarshimaitra** [Bitshala/website-v2#109]
V2 website should contain details of our reading clubs. 

We are currently running 3 Reading Clubs:

- General Reading (Bitcoin dev philosophy)
- Optech Reading
- Nostr NIPs reading.

All these should be included in a single page. Each section should link to the relevant club GitHub readme.

Host for each club:

- General: Shreyan
- Optech: Faisal
- Nostr NIPs: Basanta

**Comment by paperpsych** [comment]
@rajarshimaitra @setusaurabh Please elaborate on the details that need to be added to the reading club page?

### Here's what I have in mind so far:

- The page first shows the current reading clubs that are going on and then the ones that have happened in the past
- All the reading clubs will be mentioned on one page with their poster and details
- The details will be the moderator, the frequency, title, description, tag (beginner/adv. level)
- If there are recordings on YT, a CTA button or something to let people click and see the YT video

What else should be there?

**Comment by setusaurabh** [comment]
imo the Bitcoin Reading Club page should have these info:
 
- current ongoing reading club + how to subscribe/follow/RSVP that
- previous reading clubs that we covered + youtube link in case they want to see how it was

**Comment by setusaurabh** [comment]
We should create 2 separate pages for this. 
Each page should have 
- Upcoming event and previous events just like BitDevs
- Previous youtube uploads just like PR review page
