### ISSUE TITLE
Different Banners for Discord Community and Study Cohort

### ISSUE THREAD

**Issue by setusaurabh** [Bitshala/website-v2#113]
We'd need a separate banner for the "Discord community" card from the "Study cohort" card. Currently they both are same.

<img width="1631" alt="Screenshot 2024-01-03 at 4 30 10 PM" src="https://github.com/Bitshala/website-v2/assets/7311768/87376f58-b1cc-40ef-8dad-abdb83408612">
<img width="1625" alt="Screenshot 2024-01-03 at 4 30 15 PM" src="https://github.com/Bitshala/website-v2/assets/7311768/6d60a716-eaf6-44e2-bb12-a17cd07dfa12">

**Comment by paperpsych** [comment]
@keraliss 

Please change the banner to:


![Image](https://github.com/Bitshala/website-v2/assets/149538435/d5a8e609-f92b-4595-b82d-5441c11d2b4f)
