### ISSUE TITLE
opengraph integration

### ISSUE THREAD

**Issue by theanmolsharma** [Bitshala/website-v2#114]
This will allow us to customize how Bitshala content will appear on search engines and social platforms.
https://www.opengraph.xyz/url/https%3A%2F%2Fbitshala.org

**Comment by paperpsych** [comment]
Check this out, if it seems good for now, please let me know - I'll put it on drive...

![Bitshala Preview](https://github.com/Bitshala/website-v2/assets/149538435/e76de3a8-3842-45a1-8399-52c51c42fe1b)

I'll design a better one later.
