### ISSUE TITLE
Coming Soon Poster for April Halving Event

### ISSUE THREAD

**Issue by setusaurabh** [Bitshala/website-v2#125]
Need a coming soon poster for the April Halving Event. Lets initially share the Figma file so that different teams can take it up from there, including us.

Info about the event : 

About Halving Meetup - https://docs.google.com/document/d/1SvD3XqsjU5uJuZmlTkTAYc_oUbn_BF1qnf_1ladpcr0/edit

https://drive.google.com/drive/folders/1DklDWDkwthnZ2LYku6lMLTBK7Le8Pmxk

Europe is also having a halving party - https://bitcoinfilmfest.com/europeanhalvingparty/ just for reference.

**Comment by paperpsych** [comment]
@setusaurabh  Already shared but here it is again... [figma link](https://www.figma.com/file/WGVKySlr7jbkleCaxBArDE/Halving-Party-Design?type=design&node-id=0%3A1&mode=design&t=cyNHy55g7eEtqura-1)

Moving it to Design Review. Let me know if it can go in Done !!

**Comment by setusaurabh** [comment]
For now, it's almost done. I will wait till weekend for venue confirmation and add it and then close this ticket.

**Comment by setusaurabh** [comment]
For the following images - https://www.figma.com/file/WGVKySlr7jbkleCaxBArDE/Halving-Party-Design?type=design&node-id=3-1078&mode=design&t=Lq29n1DzeLvZUy3l-0

pls put them in the format/size to go on meetup & luma. 

For e.g. in the following image:

![Image](https://github.com/Bitshala/website-v2/assets/7311768/1b1fa6e7-410f-4250-979a-4cb72a88da47)

we will modify the following -

Label: Celebrate Bitcoin Halving with us!

Organisers: logos 

CTA: RSVP to join us at! <Location>

**Comment by paperpsych** [comment]
@setusaurabh 

![Image](https://github.com/Bitshala/website-v2/assets/149538435/8c7e31c8-0753-4431-97af-5fed34576291)

The size is good for meetup.com page, for luma it needs to be square, i'll design and send... but first tell me if the poster looks good?

**Comment by paperpsych** [comment]
I've not added the CTA because that stuff will be there in the tweet.

**Comment by setusaurabh** [comment]
Looks good to go! 

Please create the sizes for meetup and lu.ma event as well and may place in the same figma. 

Also pls let me know how to download this missing font for any future text changes?
<img width="681" alt="Screenshot 2024-03-20 at 8 45 25 AM" src="https://github.com/Bitshala/website-v2/assets/7311768/ea57b033-9ea8-47b7-87bb-bd2ff829aaa4">

**Comment by paperpsych** [comment]
You don't need to install the fonts unless you need to make changes. The size that you see in figma is the one we use on meetup. For Luma it'll be a square, I can send it by monday. I'm travelling to lucknow tonight and will be in the train for 2 days. I'll try sending the poster on sunday too but please expect it till monday !!

**Comment by setusaurabh** [comment]
need font so that i can change the text b/c location might change, and we may have to update everyone, when it does and ask everyone to update their posters as well.
 
If fonts aren't with me - there would be a blocker on you for changes.

**Comment by paperpsych** [comment]
[Poly sans.zip](https://github.com/Bitshala/website-v2/files/14752900/Poly.sans.zip)
[Boldine Complete Font Family.zip](https://github.com/Bitshala/website-v2/files/14752939/Boldine.Complete.Font.Family.zip)

Here are the fonts. PolySans is the text and Boldine is the "Bitcoin Halving" one !!

**Comment by setusaurabh** [comment]
Need luma poster as well.

**Comment by setusaurabh** [comment]
updated here - https://www.figma.com/file/WGVKySlr7jbkleCaxBArDE/Halving-Party-Design?type=design&node-id=0-1&mode=design&t=n6qqL7PMN6fwEr3T-0
