### ISSUE TITLE
Q&A in cohort pages don't open on mobile 

### ISSUE THREAD

**Issue by setusaurabh** [Bitshala/website-v2#127]
![Screenshot_20240319-090226.jpg](https://github.com/Bitshala/website-v2/assets/7311768/02a15252-7fde-4888-a2b0-be3918e2444f)

Try tapping on question in mobile phone. The answers don't open up.

This is a bug in cohorts page.

**Comment by keraliss** [comment]
![Screenshot_20240319_092803_Chrome](https://github.com/Bitshala/website-v2/assets/145189844/003ac392-e740-412b-a481-37f0aba96b48)
Working fine for me. Can anyone else check whether working for them or not!

**Comment by rajarshimaitra** [comment]
Can this be closed?

**Comment by keraliss** [comment]
I think we can close this
