### ISSUE TITLE
Bug - BPD banner states 8 week but it should be 6 weeks

### ISSUE THREAD

**Issue by setusaurabh** [Bitshala/website-v2#133]
Please update the banner here - https://bitshala.org/cohorts/bpd/

The cohort is 6 weeks long.

**Comment by keraliss** [comment]
i'll need the image of the banner in order to update it. @paperpsych can you please provide?

**Comment by paperpsych** [comment]
Yeah, one sec...

**Comment by paperpsych** [comment]
@keraliss , the image used in the website is an older placeholder thing.

The updated design: https://discord.com/channels/1104831812720656540/1104841915867861052/1221794339521302609
