### ISSUE TITLE
[bug] The home page carousel. 

### ISSUE THREAD

**Issue by rajarshimaitra** [Bitshala/website-v2#134]
The home page event carousel layouts do not match for all the slides.

The slider button changes position for each item as well the the text items change alignments from slide to slide. 

`Bitcoin Core Review Club` title text overflows into 2nd line.

cc @keraliss @paperpsych

**Comment by keraliss** [comment]
was thinking of using the same carousel we are using for the meetup page here. already showed it to @paperpsych

**Comment by rajarshimaitra** [comment]
Any layout that remains consistent with each slides will work..
