### ISSUE TITLE
Apprenticeship Page

### ISSUE THREAD

**Issue by paperpsych** [Bitshala/website-v2#148]
Apprenticeship Page - 5 Sections

**Section 01: Hero Section**
Headline, sub-headline, and CTA

**Section 02: About/Intro**
Should answer things - What is it, who is it for, how to join.

**Section 03: List view of Current Apprentices**
Should throw more light on the project, it's description.

**Section 04: Projects available for contribution**

**Section 05: Application Form**

**Comment by rajarshimaitra** [comment]
ACK on basic design.. Below are few comments.

- Lets not mention Community Champ in the hero section. I am also not fixated on the term. We can come up with something better. The hero section can say "Contribute to Bitcoin FOSS or host technical study clubs with Bitshala's paid apprenticeship program".

- The How to join section copy has to be fully changed.. Its not really saying how to join. Just reiterating the who it is for again. On how to join we can add, "apply for developer position" and/or "suggest technical study clubs you wanna host". 

- The Explore The Comm Champ needs to be changed. The idea is that the applicant have to suggest their own idea.. And we will show case all the existing ideas people are doing already. Unlike the Dev projects, they CANNOT choose from the existing project. They have to come up with something new. We need to convey that clearly. 

- The Application form will need to be different for dev and comm champs. 

If there is a figma file we can put comments into, I think that will be faster..

**Comment by setusaurabh** [comment]
as regards the form - here's the Btrust form https://btrust.homerun.co/btrust-builders-application/en/apply?&step=1

@rajarshimaitra and i can discuss and update the existing fields if some more fields might be relevant

**Comment by setusaurabh** [comment]
@rajarshimaitra closing this apprenticeship page task. And creating a new ticket for apprenticeship page updates
