### ISSUE TITLE
Showing supporters/backers on Home page

### ISSUE THREAD

**Issue by setusaurabh** [Bitshala/website-v2#150]
BitShala is a developer school supported by grants from HRF, Btrust, and others. We need to incorporate this in the home - page. Modifying the existing home page to do so is needed.

A new thin section needs to be introduced before subscribe sections.

This section will include. The copy will need to be decided whether to call them Partners, Collaborators, Supporters. Think Supporters will be fine! or Supporter and Collaborator.

Collaborator : HRF, BTrust

Supporter: Chaincode, Summer of Bitcoin,

**Comment by setusaurabh** [comment]
Good job @paperpsych. Does the job without drawing a lot of attention.

But can the font of "Our Supporters and Collaborators" be checked to confirm if this is optimum?

**Comment by paperpsych** [comment]
I can increase the font size a bit. Rest if it's good to go, we'll pass it on to Keraliss !!

**Comment by setusaurabh** [comment]
@paperpsych if you can post the final logos, we can pick up the collaborators and supporters on the current website. If chaincode has not okayed, we can remove them too.

cc @keraliss 
A more polished one can be picked up in new home - page.
