### ISSUE TITLE
Update Next cohort date and make it dynamic

### ISSUE THREAD

**Issue by setusaurabh** [Bitshala/website-v2#151]
We need to update the date to 22nd June.

![Image](https://github.com/Bitshala/website-v2/assets/7311768/b3a3f0c7-5d85-4a78-9db0-8bb5ecd5d991)

Also beyond 22nd June, it should automatically change. If the current data > next cohort date, the following logic could be used to change it: 

- Update the cohort start date to the nearest next Friday if any cohort is accepting registrations

- Update the cohort start date to next month if and omit the date for e.g. April, May, June, etc, if no cohort is accepting registrations. For comparison purposes keep it in DB as 0th Day of April. (so the moment someone looks at the website on 1st Aril the date will either be shown to be the upcoming friday or the next month)

**Comment by paperpsych** [comment]
@keraliss
