### ISSUE TITLE
Design the website page for this community space

### ISSUE THREAD

**Issue by paperpsych** [Bitshala/website-v2#160]
Keeping the design super simple and using similar elements as previous pages for ease development.

**Comment by paperpsych** [comment]
@rajarshimaitra @setusaurabh here's the layout. Copy is tentative as always, layout needs to finalized. Lmk your feedback. [Figma here](https://www.figma.com/design/1aJvem7OvIRmkOmtk3YW0Y/Team-Access?node-id=960-7468&t=6tj9ZELyjGCtvmVf-1)

![Image](https://github.com/Bitshala/website-v2/assets/149538435/2b65e761-8b73-4627-81da-d775677d2624)

- "Tell me more" on event cards takes them to Luma registration.
- The external link button in "previous events" cards take to meetup where we must be having pictures of the event uploaded

Baaki let me know :)

**Comment by rajarshimaitra** [comment]
ACK on the layout and copy. No major modification from myside. Later on we can update the twitter wallet when we have data.

**Comment by rajarshimaitra** [comment]
The primary CTA could be "Checkout the next events".

**Comment by paperpsych** [comment]
@rajarshimaitra So then we put out this page on 22nd. Then after the event we'll add "BITDEVS" as previous event and the pictures of it.


![Image](https://github.com/Bitshala/website-v2/assets/149538435/c4dd7e6f-95b4-45c6-b5ca-f7d8dcbdf7eb)

**Comment by paperpsych** [comment]
@rajarshimaitra 


![Image](https://github.com/Bitshala/website-v2/assets/149538435/f9368d3c-d3db-44b0-8c3b-6dfce80979c4)
