### ISSUE TITLE
[LBTCL] Syllabus

### ISSUE THREAD

**Issue by emjshrx** [Bitshala/website-v2#35]
<img width="533" alt="Screenshot 2023-11-19 at 12 23 52 PM" src="https://github.com/Bitshala/website-v2/assets/32434322/d1fba575-bd43-4399-bbc5-b00dde60e5f5">

**Comment by emjshrx** [comment]
Can be made with the generic collapsable list

**Comment by keraliss** [comment]
This is also a static item, with nothing to expand into. at least that's what i know!
