### ISSUE TITLE
[design] Align carousel button design

### ISSUE THREAD

**Issue by rajarshimaitra** [Bitshala/website-v2#66]
The carousel button should be similar to other buttons with a dotted outline. 

The whole carousel should be clickable.

![image](https://github.com/Bitshala/website-v2/assets/36541669/abb21af7-ef18-402d-b072-5b81d46b7d32)

**Comment by keraliss** [comment]
This is the old design, the newer one has the updated button. 
![Screenshot from 2023-12-06 19-08-56](https://github.com/Bitshala/website-v2/assets/145189844/599cb4d1-31fa-4478-9f45-20d3a3165ab5)

**Comment by keraliss** [comment]
and what about the entire thing being clickable? should it redirect to the intended page wherever you click?

**Comment by emjshrx** [comment]
Imo, the image and the tell me more only should be clickable

**Comment by rajarshimaitra** [comment]
> Imo, the image and the tell me more only should be clickable

@setusaurabh you okay with it? 

I don't have any issue either way.

**Comment by setusaurabh** [comment]
I think the whole thing should be clickable. On phone the card will be visible and people can scroll next or click and explore more. Locating the button would be too good for user to locate.
