### ISSUE TITLE
Add back home page to nav menu

### ISSUE THREAD

**Issue by emjshrx** [Bitshala/website-v2#78]
Things getting confusing without home option in navigation menu

**Comment by keraliss** [comment]
![image](https://github.com/Bitshala/website-v2/assets/145189844/141d9206-9728-4e28-b373-c529c5b7253d)
so you are suggesting a home button here, right? before "cohort", under the orange line?

**Comment by emjshrx** [comment]
> ![image](https://private-user-images.githubusercontent.com/145189844/291865817-141d9206-9728-4e28-b373-c529c5b7253d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNjkyNzYsIm5iZiI6MTcwMzA2ODk3NiwicGF0aCI6Ii8xNDUxODk4NDQvMjkxODY1ODE3LTE0MWQ5MjA2LTk3MjgtNGUyOC1iMzczLWM1MjljNWI3MjUzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMFQxMDQyNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZDM1MjcyMTc1MTU4YmJhY2ZiYWJkNmMwY2E0ZjBlMTMxOWIxODJmM2NlMGNjMDU0YmU1NzAzNmY0ZGFjYjlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DZY7o6NmZrqGixrqIXdU5tV9gOXuUMIeHPfDmxsMEtA) so you are suggesting a home button here, right? before "cohort", under the orange line?

Yes
