### ISSUE TITLE
Meet the TAs Cards in cohorts have wrong description and also look different from the ones on main page

### ISSUE THREAD

**Issue by emjshrx** [Bitshala/website-v2#84]
Just copy paste the one in main page and use a loop

**Comment by emjshrx** [comment]
Also we need to add the github and twitter links

**Comment by keraliss** [comment]
![Uploading Screenshot from 2023-12-23 15-57-45.png…]()

**Comment by keraliss** [comment]
![Screenshot from 2023-12-23 15-57-45](https://github.com/Bitshala/website-v2/assets/145189844/e91cde72-b3ff-42be-9390-589e9eb1b228)
