### ISSUE TITLE
Links are wrong in footer

### ISSUE THREAD

**Issue by emjshrx** [Bitshala/website-v2#86]

**Comment by keraliss** [comment]
![Screenshot from 2023-12-22 18-36-17](https://github.com/Bitshala/website-v2/assets/145189844/8630dfc6-7159-4249-959e-0f849629cd58)
Are you talking about this column?
also, we don't have an Instagram, so should i remove it?

**Comment by emjshrx** [comment]
All links we’re wrong when i made. Just make sure all are correct and remove whats unnecessary. Even in other columns

**Comment by keraliss** [comment]
okay
