### ISSUE TITLE
Final Issue for V1

### ISSUE THREAD

**Issue by emjshrx** [Bitshala/website-v2#93]
@rajarshimaitra please give ack when we are ready so that we can update github config to point to bitshala.org and mark this as V1 of this project

**Comment by rajarshimaitra** [comment]
Need updated testimonials. Setu shared them in the channel. 

![image](https://github.com/Bitshala/website-v2/assets/36541669/b7f10dee-5fd7-4918-b304-67f308ca4142)

**Comment by rajarshimaitra** [comment]
Let's skip the deep dive carousel for V1. Will add them in V2.

![image](https://github.com/Bitshala/website-v2/assets/36541669/2a8f3c9d-bc4c-4e5c-bb89-ecf055becf0a)

**Comment by rajarshimaitra** [comment]
Is the Advisor Title meant to be this big? 

![image](https://github.com/Bitshala/website-v2/assets/36541669/adeb735f-36dc-486c-9ded-f8b10982c1ab)

**Comment by rajarshimaitra** [comment]
We don't have a Insta.. 

Also the second column could be. Home, Team, Contact.

Home -> goes to home page
Team -> goes to team list
Contact -> opens up mail client with contact@bitshala.org

Later on we will have an About and Careers page   

![image](https://github.com/Bitshala/website-v2/assets/36541669/f0606db1-8be6-4d84-aee8-636af63e1cd1)

**Comment by keraliss** [comment]
![Screenshot from 2023-12-23 15-59-55](https://github.com/Bitshala/website-v2/assets/145189844/cd4aec20-e1a3-49f1-9b40-bf9157b3042b)

**Comment by emjshrx** [comment]
Lets keep this open for the final ack from @rajarshimaitra and to do config changes

**Comment by emjshrx** [comment]
completed by 865f89777fc26bf979c111ce6a4d8b2a1e8930b4
