### ISSUE TITLE
Need updated testimonials.

### ISSUE THREAD

**Issue by emjshrx** [Bitshala/website-v2#95]
Need updated testimonials. Setu shared them in the channel. 

![image](https://github.com/Bitshala/website-v2/assets/36541669/b7f10dee-5fd7-4918-b304-67f308ca4142)

_Originally posted by @rajarshimaitra in https://github.com/Bitshala/website-v2/issues/93#issuecomment-1867660759_

**Comment by keraliss** [comment]
![Screenshot from 2023-12-23 15-58-56](https://github.com/Bitshala/website-v2/assets/145189844/5618584a-bffe-4dd5-b773-0e30d2598339)
